'use strict';
const fs = require('fs');

// Block 04: Deutsch – Rechtschreibung
fs.writeFileSync('klasse05_block04_deutsch_rechtschreibung.json', JSON.stringify([
  {question:"Welches Wort ist korrekt?",options:["villeicht","vileicht","vielleicht","vieleicht"],correct:2,explanation:"vielleicht – merke: viel-leicht.",topic:"Häufige Fehler"},
  {question:"Nach kurzem Vokal schreibt man:",options:["ß","ss","s","sz"],correct:1,explanation:"Nach kurzem Vokal: -ss (Fluss, muss).",topic:"s-Schreibung"},
  {question:"Wann schreibt man Nomen groß?",options:["Nie","Nur am Satzanfang","Immer","Nur bei Namen"],correct:2,explanation:"Alle Nomen werden großgeschrieben: der Hund, die Schule.",topic:"Großschreibung"},
  {question:"Welches Wort enthält einen Umlaut?",options:["Hund","Haus","Tür","Ball"],correct:2,explanation:"Umlaute: ä, ö, ü. Tür enthält ü.",topic:"Umlaute"},
  {question:"Wann benutzt man 'dass'?",options:["Als Artikel","Als Konjunktion für Nebensätze","Immer statt das","Nie"],correct:1,explanation:"'dass' leitet Nebensätze ein. 'das' ist Artikel/Pronomen.",topic:"das/dass"},
  {question:"Welches Wort schreibt man mit ie?",options:["lid","lied","Lied","Lied und lied"],correct:2,explanation:"Lied mit ie – langer i-Laut.",topic:"ie-Schreibung"},
  {question:"'seit' oder 'seid'?",options:["seit immer","seid immer","seit = Zeit; seid = Verb (ihr seid)","Beide gleich"],correct:2,explanation:"seit (Zeit): seit gestern. seid (Verb): ihr seid.",topic:"Verwechslungen"},
  {question:"Welches Wort hat Doppelkonsonant?",options:["laufen","essen","Schule","Tür"],correct:1,explanation:"essen hat ss nach kurzem Vokal.",topic:"Doppelkonsonanten"},
  {question:"Welches Wort ist richtig?",options:["warscheinlich","wahrscheinlich","Wahrscheinlic","wahrscheinlic"],correct:1,explanation:"wahrscheinlich – h gehört zum Stamm wahr.",topic:"Häufige Fehler"},
  {question:"Was ist ein Fremdwort?",options:["Hund","Computer","Schule","Baum"],correct:1,explanation:"Computer stammt aus dem Englischen.",topic:"Fremdwörter"},
  {question:"Wann steht nach Doppelpunkt ein Großbuchstabe?",options:["Nie","Immer","Nur bei direkter Rede oder vollst. Satz","Nur bei Aufzählungen"],correct:2,explanation:"Er rief: Hilfe! oder wenn ein vollständiger Satz folgt.",topic:"Zeichensetzung"},
  {question:"Was ist richtig?",options:["das selbe","dasselbe","daßselbe","Das selbe"],correct:1,explanation:"dasselbe – zusammengeschrieben als Pronomen.",topic:"Zusammenschreibung"},
  {question:"Silbentrennung von 'laufen':",options:["l-aufen","lau-fen","lauf-en","la-ufen"],correct:1,explanation:"lau-fen – Trennung nach Sprechsilben.",topic:"Silbentrennung"},
  {question:"Was sind Umlaute?",options:["a, e, i, o, u","ä, ö, ü","ss und ß","ch und sch"],correct:1,explanation:"Umlaute: ä, ö, ü.",topic:"Umlaute"},
  {question:"Wann benutzt man Apostroph?",options:["Bei allen Abkürzungen","Bei Auslassung von Buchstaben","Vor jedem s","Immer vor Genitiv"],correct:1,explanation:"Apostroph: geht es → geht's.",topic:"Zeichensetzung"},
  {question:"Korrekte Schreibung:",options:["auf wiedersehen","auf Wiedersehen","aufwiedersehen","AufWiedersehen"],correct:1,explanation:"auf Wiedersehen – getrennt, Wiedersehen als Nomen groß.",topic:"Groß-/Kleinschreibung"},
  {question:"Welches Wort hat ck?",options:["Haken","Zucker","Flasche","Wagen"],correct:1,explanation:"Zucker mit ck nach kurzem Vokal.",topic:"Doppelkonsonanten"},
  {question:"Wann steht Komma vor 'weil'?",options:["Nie","Immer","Weil leitet Nebensatz ein","Nur am Satzanfang"],correct:2,explanation:"Ich bleibe zu Hause, weil ich krank bin.",topic:"Zeichensetzung"},
  {question:"Was schreibt man mit ß?",options:["Fluss","muss","Straße","essen"],correct:2,explanation:"Nach langem Vokal: ß (Straße). Nach kurzem: ss (Fluss).",topic:"s-Schreibung"},
  {question:"Richtige Pluralform von 'Foto':",options:["die Fotos","die Fotoen","die Fotoes","die Foto"],correct:0,explanation:"Fremdwörter auf -o: Plural mit -s.",topic:"Fremdwörter"},
  {question:"Was ist korrekt?",options:["Abenteuer","Abentheuer","abenteuer","Abendteuer"],correct:0,explanation:"Abenteuer – ohne h, als Nomen groß.",topic:"Häufige Fehler"},
  {question:"'sofort' oder 'so fort'?",options:["so fort","sofort","So Fort","so-fort"],correct:1,explanation:"sofort – Adverb, zusammengeschrieben.",topic:"Zusammenschreibung"},
  {question:"Was enthält Dehnungs-h?",options:["Katze","Stahl","Tasse","Lampe"],correct:1,explanation:"Stahl: a wird durch h gedehnt.",topic:"Dehnung"},
  {question:"'wenn' oder 'wen'?",options:["wen es regnet","wenn es regnet","Wen es regnet","wänn es regnet"],correct:1,explanation:"wenn (Konjunktion). wen = Akkusativ von wer.",topic:"wenn/wen"},
  {question:"Kompositum korrekt:",options:["raubtier","Raubtier","Raub Tier","RaubTier"],correct:1,explanation:"Komposita mit Nomen groß: Raubtier.",topic:"Komposita"},
  {question:"'spazieren gehen' – korrekt?",options:["spazierengehen","spazieren gehen","Spazieren Gehen","Spazierengehn"],correct:1,explanation:"spazieren gehen – getrennt geschrieben.",topic:"Getrenntschreibung"},
  {question:"Wann wird 'man' kleingeschrieben?",options:["Immer","Nur am Satzanfang groß","Als Pronomen immer klein","Immer groß"],correct:2,explanation:"man ist Indefinitpronomen, immer klein.",topic:"Groß-/Kleinschreibung"},
  {question:"Korrekte Schreibung:",options:["Kaffe","Kaffee","kaffee","Kafee"],correct:1,explanation:"Kaffee – zwei e, als Nomen groß.",topic:"Fremdwörter"},
  {question:"Was ist ein Diphthong?",options:["Doppelkonsonant","Zwielaut (ei, au, eu)","Umlaut","Dehnungs-h"],correct:1,explanation:"Diphthonge: ei (Wein), au (Baum), eu (Eule).",topic:"Lautlehre"},
  {question:"Wann benutzt man Ausrufezeichen?",options:["Nach Fragen","Nach Aufforderungen und Ausrufen","Nach Aufzählungen","Nach Nebensätzen"],correct:1,explanation:"Ausrufezeichen nach Aufforderungen: Komm her!",topic:"Zeichensetzung"},
  {question:"Richtige Verbform:",options:["er schläpft","er schlaeft","er schläft","er schleift"],correct:2,explanation:"schlafen → er schläft (Umlaut a → ä).",topic:"Verben"},
  {question:"Was ist ein Laut?",options:["Ein Buchstabe","Kleinste gehörte Einheit","Ein Wort","Eine Silbe"],correct:1,explanation:"Laute sind die kleinsten gehörten Spracheinheiten.",topic:"Lautlehre"},
  {question:"Wie viele Silben hat 'Schmetterling'?",options:["2","3","4","1"],correct:1,explanation:"Schmet-ter-ling = 3 Silben.",topic:"Silbentrennung"},
  {question:"'wie viel' oder 'wieviel'?",options:["Wieviel","wie viel","WieViel","wie-viel"],correct:1,explanation:"wie viel – seit Rechtschreibreform getrennt.",topic:"Getrenntschreibung"},
  {question:"Was bedeutet Dehnung?",options:["Konsonant verdoppeln","Langen Vokal markieren (h, ie)","Wort verlängern","Silbe weglassen"],correct:1,explanation:"Dehnung: Strahl (h), Lied (ie).",topic:"Dehnung"},
  {question:"Korrekte Präteritumform 'haben' (ich):",options:["ich hatte","ich habe","ich haben","ich hat"],correct:0,explanation:"Präteritum: ich hatte.",topic:"Verben"},
  {question:"Was ist korrekt?",options:["das Kind","Das kind","daß Kind","das kind"],correct:0,explanation:"das Kind – Artikel klein, Nomen groß.",topic:"Groß-/Kleinschreibung"},
  {question:"Korrekte Schreibung von 'Entschuldigung':",options:["Entshuldigung","Entschuldigung","Entschudigung","entschuldigung"],correct:1,explanation:"Entschuldigung mit sch.",topic:"Häufige Fehler"},
  {question:"Was bedeutet 'trotzdem'?",options:["trotz dem","Trotzdem","trotzdem","Trotz dem"],correct:2,explanation:"trotzdem – Konjunktion, zusammengeschrieben, klein.",topic:"Konjunktionen"},
  {question:"Was ist korrekt?",options:["die Entschuldigung","Die entschuldigung","Die Entschuldigung","die entschuldigung"],correct:0,explanation:"die Entschuldigung – Artikel klein, Nomen groß.",topic:"Großschreibung"}
], null, 2), 'utf8');
console.log('Block 04: 40 Fragen');

// Block 05: Englisch – Grundlagen
fs.writeFileSync('klasse05_block05_englisch.json', JSON.stringify([
  {question:"What is the English word for Hund?",options:["cat","dog","bird","fish"],correct:1,explanation:"Hund = dog.",topic:"Vokabular"},
  {question:"How do you say Guten Morgen in English?",options:["Good night","Good afternoon","Good morning","Good evening"],correct:2,explanation:"Guten Morgen = Good morning.",topic:"Begrüßung"},
  {question:"Which sentence is correct?",options:["I am 11 years old.","I have 11 years.","I is 11 years old.","I am 11 year old."],correct:0,explanation:"I am ... years old.",topic:"Grammatik"},
  {question:"What does pencil mean?",options:["Lineal","Radiergummi","Bleistift","Heft"],correct:2,explanation:"pencil = Bleistift.",topic:"Schulsachen"},
  {question:"Plural of book:",options:["books","bookes","booky","bookies"],correct:0,explanation:"book + s = books.",topic:"Grammatik"},
  {question:"What color is the sky?",options:["green","red","blue","yellow"],correct:2,explanation:"The sky is blue.",topic:"Farben"},
  {question:"What does school mean?",options:["hospital","school","library","store"],correct:1,explanation:"school = Schule.",topic:"Vokabular"},
  {question:"What is 5 + 3 in English?",options:["six","nine","eight","seven"],correct:2,explanation:"8 = eight.",topic:"Zahlen"},
  {question:"How do you greet in the afternoon?",options:["Good morning","Good night","Good afternoon","Good bye"],correct:2,explanation:"Good afternoon = Guten Nachmittag.",topic:"Begrüßung"},
  {question:"To be (1st person singular):",options:["is","are","am","be"],correct:2,explanation:"I am. You are. He/she/it is.",topic:"Verben"},
  {question:"What does family mean?",options:["Freund","Familie","Schule","Haus"],correct:1,explanation:"family = Familie.",topic:"Vokabular"},
  {question:"Ich heisse ... auf Englisch:",options:["I called ...","My name is ...","I am called my ...","Name me is ..."],correct:1,explanation:"My name is ...",topic:"Vorstellen"},
  {question:"Opposite of big:",options:["tall","large","small","fat"],correct:2,explanation:"big (groß) – small (klein).",topic:"Adjektive"},
  {question:"What does Monday mean?",options:["Dienstag","Mittwoch","Montag","Donnerstag"],correct:2,explanation:"Monday = Montag.",topic:"Wochentage"},
  {question:"What does apple mean?",options:["Orange","Apfel","Banane","Erdbeere"],correct:1,explanation:"apple = Apfel.",topic:"Essen"},
  {question:"She ___ a cat:",options:["have","has","haves","having"],correct:1,explanation:"3. Person Singular: She has.",topic:"Grammatik"},
  {question:"What does 'What time is it?' mean?",options:["Wie heißt du?","Wie alt bist du?","Wie spät ist es?","Wo ist es?"],correct:2,explanation:"What time is it? = Wie spät ist es?",topic:"Uhrzeiten"},
  {question:"January auf Deutsch:",options:["Juli","Juni","Januar","Februar"],correct:2,explanation:"January = Januar.",topic:"Monate"},
  {question:"Danke auf Englisch:",options:["Please","Sorry","Thank you","Hello"],correct:2,explanation:"Danke = Thank you.",topic:"Höflichkeit"},
  {question:"Numbers 1-5 in English:",options:["one, two, three, four, five","one, two, tree, four, fife","wan, tu, tri, fo, fai","ein, zwei, drei, vier, fünf"],correct:0,explanation:"1-5: one, two, three, four, five.",topic:"Zahlen"},
  {question:"What does bedroom mean?",options:["Badezimmer","Küche","Schlafzimmer","Wohnzimmer"],correct:2,explanation:"bedroom = Schlafzimmer.",topic:"Haus"},
  {question:"There is (correct use):",options:["There is two cats.","There is a cat.","There are a cat.","There is cat."],correct:1,explanation:"There is (Singular): There is a cat.",topic:"Grammatik"},
  {question:"What is your name? auf Deutsch:",options:["Wie alt bist du?","Wie heißt du?","Wo wohnst du?","Wie geht es dir?"],correct:1,explanation:"What is your name? = Wie heißt du?",topic:"Vorstellen"},
  {question:"What does teacher mean?",options:["Schüler","Direktor","Lehrer","Hausmeister"],correct:2,explanation:"teacher = Lehrer.",topic:"Schule"},
  {question:"Plural of child:",options:["childs","childes","children","childrens"],correct:2,explanation:"Unregelmäßig: child – children.",topic:"Grammatik"},
  {question:"What does sunny mean?",options:["regnerisch","wolkig","sonnig","windig"],correct:2,explanation:"sunny = sonnig.",topic:"Wetter"},
  {question:"How old are you? (richtig):",options:["How old have you?","How old is you?","How old are you?","How old do you?"],correct:2,explanation:"How old are you? = Wie alt bist du?",topic:"Fragen"},
  {question:"What does breakfast mean?",options:["Mittagessen","Abendessen","Frühstück","Snack"],correct:2,explanation:"breakfast = Frühstück.",topic:"Essen"},
  {question:"I like ... bedeutet:",options:["Ich mag ...","Ich habe ...","Ich bin ...","Ich will ..."],correct:0,explanation:"I like ... = Ich mag ...",topic:"Grammatik"},
  {question:"rot auf Englisch:",options:["blue","green","yellow","red"],correct:3,explanation:"rot = red.",topic:"Farben"},
  {question:"What does homework mean?",options:["Hausarbeit","Hausaufgaben","Heimarbeit","Hausordnung"],correct:1,explanation:"homework = Hausaufgaben.",topic:"Schule"},
  {question:"Plural of mouse:",options:["mouses","mice","mices","mousey"],correct:1,explanation:"mouse – mice (unregelmäßig).",topic:"Grammatik"},
  {question:"winter auf Deutsch:",options:["Frühling","Sommer","Herbst","Winter"],correct:3,explanation:"winter = Winter.",topic:"Jahreszeiten"},
  {question:"Bitte auf Englisch:",options:["Thank you","Sorry","Please","Excuse me"],correct:2,explanation:"Bitte = Please.",topic:"Höflichkeit"},
  {question:"He ___ football (Präsens):",options:["play","plays","playing","played"],correct:1,explanation:"He plays (+ s bei 3. Person Singular).",topic:"Verben"},
  {question:"Where do you live? auf Deutsch:",options:["Wie alt bist du?","Wo wohnst du?","Was machst du?","Wer bist du?"],correct:1,explanation:"Where do you live? = Wo wohnst du?",topic:"Fragen"},
  {question:"Mittwoch auf Englisch:",options:["Monday","Tuesday","Wednesday","Thursday"],correct:2,explanation:"Mittwoch = Wednesday.",topic:"Wochentage"},
  {question:"I don't know bedeutet:",options:["Ich weiß es","Ich glaube nicht","Ich weiß es nicht","Ich will nicht"],correct:2,explanation:"I don't know = Ich weiß es nicht.",topic:"Grammatik"},
  {question:"What does cat mean?",options:["Hund","Vogel","Katze","Fisch"],correct:2,explanation:"cat = Katze.",topic:"Vokabular"},
  {question:"What does school bag mean?",options:["Schulheft","Schulranzen","Schultafel","Schulbank"],correct:1,explanation:"school bag = Schulranzen.",topic:"Schulsachen"}
], null, 2), 'utf8');
console.log('Block 05: 40 Fragen');

// Block 06: Erdkunde – Deutschland
fs.writeFileSync('klasse05_block06_erdkunde_deutschland.json', JSON.stringify([
  {question:"Hauptstadt Deutschlands?",options:["Hamburg","München","Berlin","Frankfurt"],correct:2,explanation:"Berlin ist die Hauptstadt Deutschlands.",topic:"Deutschland"},
  {question:"Welcher Fluss fließt durch Köln?",options:["Elbe","Donau","Rhein","Main"],correct:2,explanation:"Der Rhein fließt durch Köln.",topic:"Flüsse"},
  {question:"Wie viele Bundesländer hat Deutschland?",options:["12","14","16","18"],correct:2,explanation:"Deutschland hat 16 Bundesländer.",topic:"Bundesländer"},
  {question:"Größtes Bundesland nach Fläche?",options:["Bayern","NRW","Baden-Württemberg","Niedersachsen"],correct:0,explanation:"Bayern (70.550 km²) ist das größte Bundesland.",topic:"Bundesländer"},
  {question:"Wo liegt Hamburg?",options:["An der Ostsee","An der Nordsee","Am Rhein","Im Binnenland"],correct:1,explanation:"Hamburg liegt an der Elbe nahe der Nordsee.",topic:"Meere"},
  {question:"Höchster Berg Deutschlands?",options:["Brocken","Zugspitze","Feldberg","Watzmann"],correct:1,explanation:"Die Zugspitze (2962 m) ist Deutschlands höchster Berg.",topic:"Berge"},
  {question:"Welcher Fluss mündet in die Nordsee?",options:["Isar","Spree","Elbe","Neckar"],correct:2,explanation:"Die Elbe mündet bei Cuxhaven in die Nordsee.",topic:"Flüsse"},
  {question:"Landeshauptstadt Bayerns?",options:["Nürnberg","Augsburg","München","Würzburg"],correct:2,explanation:"München ist die Landeshauptstadt von Bayern.",topic:"Bundesländer"},
  {question:"Gebirge im Süden Deutschlands?",options:["Harz","Alpen","Eifel","Schwarzwald"],correct:1,explanation:"Die Alpen bilden den südlichen Abschluss Deutschlands.",topic:"Gebirge"},
  {question:"Was ist ein Stadtstaat?",options:["München","Köln","Hamburg","Düsseldorf"],correct:2,explanation:"Hamburg, Bremen und Berlin sind Stadtstaaten.",topic:"Bundesländer"},
  {question:"Rostock liegt an der:",options:["Nordsee","Mittelmeer","Ostsee","Elbe"],correct:2,explanation:"Rostock liegt an der Ostsee.",topic:"Meere"},
  {question:"Bevölkerungsreichste Stadt Deutschlands?",options:["Hamburg","München","Frankfurt","Berlin"],correct:3,explanation:"Berlin hat ca. 3,7 Mio. Einwohner.",topic:"Städte"},
  {question:"Welcher Fluss fließt durch Berlin?",options:["Rhein","Elbe","Spree","Donau"],correct:2,explanation:"Die Spree fließt durch Berlin.",topic:"Flüsse"},
  {question:"Wo liegt der Schwarzwald?",options:["Bayern","Hessen","Baden-Württemberg","Rheinland-Pfalz"],correct:2,explanation:"Der Schwarzwald liegt in Baden-Württemberg.",topic:"Gebirge"},
  {question:"Längster Fluss Deutschlands?",options:["Rhein","Elbe","Donau","Weser"],correct:0,explanation:"Der Rhein ist Deutschlands längster Fluss.",topic:"Flüsse"},
  {question:"Nördlichstes Bundesland (grenzt an Dänemark)?",options:["Niedersachsen","Schleswig-Holstein","Mecklenburg-Vorpommern","Hamburg"],correct:1,explanation:"Schleswig-Holstein grenzt an Dänemark.",topic:"Bundesländer"},
  {question:"Was ist die Donau?",options:["Ein Gebirge","Ein See","Ein Fluss","Eine Region"],correct:2,explanation:"Die Donau ist Europas zweitlängster Fluss.",topic:"Flüsse"},
  {question:"Landeshauptstadt von NRW?",options:["Köln","Essen","Düsseldorf","Dortmund"],correct:2,explanation:"Düsseldorf ist Landeshauptstadt von Nordrhein-Westfalen.",topic:"Bundesländer"},
  {question:"Was ist der Harz?",options:["Ein Fluss","Mittelgebirge in Norddeutschland","Eine Stadt","Eine Küste"],correct:1,explanation:"Der Harz ist ein Mittelgebirge (Sachsen-Anhalt, Niedersachsen).",topic:"Gebirge"},
  {question:"Nachbarländer im Norden Deutschlands?",options:["Frankreich und Polen","Dänemark und Niederlande","Österreich und Schweiz","Tschechien und Belgien"],correct:1,explanation:"Norden: Dänemark und Niederlande.",topic:"Nachbarländer"},
  {question:"Was ist das Ruhrgebiet?",options:["Küstenregion","Gebirge","Dicht besiedeltes Industriegebiet in NRW","Waldgebiet"],correct:2,explanation:"Ruhrgebiet: Essen, Dortmund, Bochum.",topic:"Regionen"},
  {question:"Welcher See liegt in Bayern?",options:["Schweriner See","Chiemsee","Müritz","Bodensee"],correct:1,explanation:"Der Chiemsee liegt in Bayern.",topic:"Seen"},
  {question:"Bodensee – welche Länder?",options:["D, A, CH","D, F, CH","D, A, I","D, PL, CZ"],correct:0,explanation:"Der Bodensee liegt zwischen Deutschland, Österreich und der Schweiz.",topic:"Seen"},
  {question:"Flächenkleinste Bundesland?",options:["Saarland","Bremen","Berlin","Hamburg"],correct:1,explanation:"Bremen ist das flächenkleinste Bundesland.",topic:"Bundesländer"},
  {question:"Was ist die Norddeutsche Tiefebene?",options:["Hohes Gebirge","Flaches weites Land im Norden","Vulkangebiet","Enge Täler"],correct:1,explanation:"Die Norddeutsche Tiefebene ist durch flaches Land geprägt.",topic:"Landschaften"},
  {question:"Durch Frankfurt fließt:",options:["Rhein","Lahn","Main","Neckar"],correct:2,explanation:"Frankfurt am Main liegt am Fluss Main.",topic:"Flüsse"},
  {question:"Brocken ist:",options:["Ein Fluss im Harz","Höchster Berg im Harz (1141 m)","Eine Stadt in Sachsen","Ein See"],correct:1,explanation:"Der Brocken ist der höchste Berg im Harz.",topic:"Gebirge"},
  {question:"Bundesland das an Polen grenzt:",options:["Sachsen-Anhalt","Brandenburg","Thüringen","Bayern"],correct:1,explanation:"Brandenburg grenzt im Osten an Polen.",topic:"Bundesländer"},
  {question:"Landeshauptstadt von Sachsen?",options:["Leipzig","Chemnitz","Dresden","Zwickau"],correct:2,explanation:"Dresden ist die Landeshauptstadt von Sachsen.",topic:"Städte"},
  {question:"Fluss an der Grenze zu Polen?",options:["Elbe","Oder","Rhein","Weser"],correct:1,explanation:"Die Oder bildet mit der Neiße die Grenze zu Polen.",topic:"Flüsse"},
  {question:"Bevölkerungsreichstes Bundesland?",options:["Bayern","Baden-Württemberg","Nordrhein-Westfalen","Niedersachsen"],correct:2,explanation:"NRW hat ca. 18 Mio. Einwohner.",topic:"Bundesländer"},
  {question:"Was ist das Wattenmeer?",options:["Gebirgspark","Küstenschutzgebiet an der Nordsee","Waldgebiet","Flussdelta"],correct:1,explanation:"Das Wattenmeer ist UNESCO-Weltnaturerbe an der Nordsee.",topic:"Naturräume"},
  {question:"Hamburg liegt am Fluss:",options:["Rhein","Weser","Elbe","Spree"],correct:2,explanation:"Hamburg liegt an der Elbe.",topic:"Flüsse"},
  {question:"Landeshauptstadt von Thüringen?",options:["Gera","Jena","Weimar","Erfurt"],correct:3,explanation:"Erfurt ist Landeshauptstadt von Thüringen.",topic:"Städte"},
  {question:"Was ist die Lüneburger Heide?",options:["Mittelgebirge","Heidelandschaft in Niedersachsen","Flussdelta","Küste"],correct:1,explanation:"Die Lüneburger Heide ist eine weite Heidelandschaft.",topic:"Landschaften"},
  {question:"Freistaat unter den Bundesländern:",options:["Hessen und NRW","Bayern und Sachsen","NRW und Bayern","Sachsen und Niedersachsen"],correct:1,explanation:"Bayern und Sachsen tragen den Titel Freistaat.",topic:"Bundesländer"},
  {question:"Landeshauptstadt von Rheinland-Pfalz?",options:["Koblenz","Trier","Kaiserslautern","Mainz"],correct:3,explanation:"Mainz ist Landeshauptstadt von Rheinland-Pfalz.",topic:"Bundesländer"},
  {question:"Was ist die Elbphilharmonie?",options:["Schloss in Dresden","Konzerthaus in Hamburg","Rathaus in Berlin","Museum in München"],correct:1,explanation:"Die Elbphilharmonie ist ein Konzerthaus in Hamburg.",topic:"Sehenswürdigkeiten"},
  {question:"Wie heißt das Brandenburger Tor?",options:["Ein Museum in München","Ein historisches Stadttor in Berlin","Eine Kirche in Hamburg","Ein Schloss in Potsdam"],correct:1,explanation:"Das Brandenburger Tor ist Berlins bekanntestes Wahrzeichen.",topic:"Sehenswürdigkeiten"},
  {question:"Bundesland mit Kiel als Landeshauptstadt:",options:["Niedersachsen","Mecklenburg-Vorpommern","Schleswig-Holstein","Hamburg"],correct:2,explanation:"Kiel ist die Landeshauptstadt von Schleswig-Holstein.",topic:"Bundesländer"}
], null, 2), 'utf8');
console.log('Block 06: 40 Fragen');
